<div class="container">
    <h2>Edit Order</h2>
    <p><?php echo $this->flash->output() ?></p>
    <?php echo $this->tag->form("index/edit"); ?>
        <div class="form-group">
            <label for="quantity">Quantity</label>
            <?php echo $form->render('quantity'); ?>
        </div>
        <div class="form-group">
            <label for="quantity">Item Price</label>
            <?php echo $form->render('item_price'); ?>
        </div>
        <div class="form-group">
            <label for="quantity">Item Name</label>
            <?php echo $form->render('item_name'); ?>
        </div>
        <div class="form-group">
            <?php echo $form->render('csrf', ['value'=>  $this->security->getSessionToken()]); ?>
            <?php echo $form->render('order_id'); ?>
            <?php echo $form->render('id'); ?>
        </div>
        <div class="form-group">
            <?php echo $form->render('submit'); ?>
        </div>
    </form>
</div>