<div class="container">
    <h2>Login</h2>
    <p><?php echo $this->flash->output() ?></p>

    <?php echo $this->tag->form("index/login"); ?>

        <div class="form-group">
            <label for="email">E-Mail</label>
            <?php echo $form->render('email'); ?>
        </div>

        <div class="form-group">
            <label for="password">Password</label>
            <?php echo $form->render('password'); ?>
        </div>

        <div class="form-group">
            <?php echo $form->render('submit'); ?>
        </div>
        
        <input type='hidden' name='<?php $this->security->getTokenKey() ?>' value='<?php $this->security->getToken() ?>'/>
    </form>
</div>