version: "3"
services:
  db:
    image: postgres:11
    container_name: billbox_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: root
      POSTGRES_DB: billbox
    volumes:
      - ./pgdata/:/var/lib/postgresql/data:rw
  app:
    container_name: billbox_app
    build: .
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    expose:
      - "8080"
